name: Checks

on:
  pull_request:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  checks:
    if: ${{ !contains(github.event.head_commit.message, '[skip-checks]') }}
    timeout-minutes: 3
    runs-on: ['ubuntu-latest']
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4.1.1

      - name: 'Set up Bun'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: 'Install Dependencies'
        shell: bash
        run: bun install

      - name: 'Lint'
        shell: bash
        run: bun lint

      - name: 'Format'
        shell: bash
        run: bun format

      - name: 'Typecheck'
        shell: bash
        run: bun typecheck

      - name: 'Build'
        shell: bash
        run: bun run build
